version: '3.8'

services:
  dev:
    image: nest_docker:local
    container_name: nestjs_api_dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    networks:
      - networknest
    depends_on:
      - mongonest
    volumes:
      - .:/usr/src
    command: npm run start:dev

  mongonest:
    image: mongo:latest
    container_name: mongonest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodata:/data/db
    ports:
      - 27018:27017
    networks:
      - networknest
    restart: always

volumes:
  mongodata:
networks:
  networknest:
    name: networknest
    driver: bridge
    ipam:
      driver: default
